# Generated by Django 4.1.5 on 2023-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('playtime_forever', models.IntegerField(default=0, verbose_name='Playtime')),
                ('img_icon_url', models.CharField(default='', max_length=250, verbose_name='Icon URL')),
                ('completed', models.BooleanField(default=False, verbose_name='Finished')),
                ('played', models.BooleanField(default=False, verbose_name='Launched')),
                ('date', models.DateField(default='2020-01-01', verbose_name='Finish date')),
                ('genre', models.CharField(default='', max_length=40, verbose_name='Genre')),
                ('plateform', models.CharField(default='', max_length=40, verbose_name='Platform')),
                ('appid', models.CharField(default=0, max_length=40, verbose_name='Appid')),
                ('last_played', models.DateField(default='2020-01-01', verbose_name='Last played')),
                ('img_url', models.CharField(default='', max_length=250, verbose_name='Image URL')),
            ],
        ),
    ]
