# Generated by Django 4.1.5 on 2023-12-15 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesLibrary', '0002_rename_plateform_video_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_game',
            name='critic',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Critic'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='gaas',
            field=models.BooleanField(default=False, verbose_name='GAAS/MMO/Multi'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='num_stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Stars'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='release_year',
            field=models.IntegerField(default=1900, verbose_name='Release year'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='unfinishable',
            field=models.BooleanField(default=False, verbose_name='Unfinishable (Sandbox, scoring...)'),
        ),
        migrations.AddField(
            model_name='video_game',
            name='update_date',
            field=models.DateField(default='2020-01-01', verbose_name='Last updated'),
        ),
    ]
